# Generated by Django 4.1 on 2024-07-02 19:56

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('faq_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='category',
            field=models.CharField(choices=[('general', 'General Queries'), ('challenge', 'The Challenge'), ('funded', 'The Funded Account')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
