# Generated by Django 4.1 on 2024-07-02 20:28

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('faq_chatbot', '0002_alter_faqs_category_alter_faqs_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
